export const ActionTypes = {
    GET_THIRTY_SIX_DATA_ACTION_REQUEST: 'GET_THIRTY_SIX_DATA_ACTION_REQUEST',
    GET_THIRTY_SIX_DATA_ACTION_SUCCESS: 'GET_THIRTY_SIX_DATA_ACTION_SUCCESS',
    GET_THIRTY_SIX_DATA_ACTION_FAILURE: 'GET_THIRTY_SIX_DATA_ACTION_FAILURE',

    GET_EVERY_THREE_HOUR_DATA_ACTION_REQUEST: 'GET_EVERY_THREE_HOUR_DATA_ACTION_REQUEST',
    GET_EVERY_THREE_HOUR_DATA_ACTION_SUCCESS: 'GET_EVERY_THREE_HOUR_DATA_ACTION_SUCCESS',
    GET_EVERY_THREE_HOUR_DATA_ACTION_FAILURE: 'GET_EVERY_THREE_HOUR_DATA_ACTION_FAILURE',
}
